/**
 * GSD Quoter — Catálogo de servicios
 * Geosolutions Source Dominicana, S.R.L.
 *
 * Fuente: tarifario interno de GSD. Los montos son PRELIMINARES y quedan
 * sujetos a complejidad y análisis previo (regla general del tarifario).
 *
 * Campos de cada servicio:
 *   id            slug único, usado por el formulario y la BD
 *   division      legal | inmobiliario | agrimensura
 *   nombre        etiqueta visible
 *   icono         nombre del icono SVG (ver public/gsd-quoter/icons.js)
 *   base          { moneda, monto } honorario de referencia, null si se cotiza a medida
 *   unidad        texto corto que explica a qué corresponde el monto base
 *   plazo         plazo declarable al cliente
 *   incluye       [] conceptos cubiertos por el honorario
 *   noIncluye     [] conceptos expresamente excluidos
 *   desglose      [] conceptos que se muestran al cliente por separado (terceros)
 *   pago          condición de pago por defecto
 *   itbisPorDefecto  si el ITBIS se marca al crear la cotización
 *   campos        campos extra que el formulario debe pedir para este servicio
 *   nota          advertencia que se imprime en la cotización
 */

const MONEDA = { USD: 'US$', DOP: 'RD$' };

/** Regla de moneda de GSD según zona y perfil del cliente. */
function monedaSugerida(zona, clienteExtranjero) {
  const z = (zona || '').toLowerCase();
  if (clienteExtranjero) return 'USD';
  if (z.includes('bávaro') || z.includes('bavaro') || z.includes('punta cana')) return 'USD';
  if (z.includes('romana')) return 'DOP';
  return 'USD';
}

const SERVICIOS = [
  // ───────────────────────── LEGAL ─────────────────────────
  {
    id: 'iguala-legal',
    division: 'legal',
    nombre: 'Iguala legal',
    icono: 'briefcase',
    base: { moneda: 'USD', monto: 1000 },
    unidad: 'por mes, nivel Essential',
    plazo: 'Servicio continuo, facturación mensual',
    niveles: [
      { id: 'essential', nombre: 'Essential', monto: 1000,
        alcance: 'Consultas, revisión documental, contratos de alcance ordinario y prevención de conflictos.' },
      { id: 'business', nombre: 'Business', monto: 1500,
        alcance: 'Todo lo de Essential, más contratos y negociación, asesoría empresarial, documentación societaria y cobros de gestión ordinaria.' },
      { id: 'corporate', nombre: 'Corporate', monto: 2500,
        alcance: 'Todo lo de Business, más derecho inmobiliario, asesoría comercial continua, coordinación de procesos legales y atención prioritaria.' },
      { id: 'legal-total', nombre: 'Legal Total', monto: 5000,
        alcance: 'Todos los servicios legales de la firma.' },
      { id: 'integral', nombre: 'Integral', monto: 8000,
        alcance: 'Todos los servicios legales más trabajo de agrimensura y todos los servicios de la firma, incluida tasación.' },
    ],
    incluye: ['Asesoría jurídica continua', 'Revisión documental del período', 'Atención por los canales acordados'],
    noIncluye: ['Procedimientos contenciosos complejos, que se cotizan de forma independiente',
                'Impuestos, tasas y derechos oficiales'],
    pago: 'Mensual por adelantado',
    itbisPorDefecto: true,
    campos: ['nivelIguala', 'duracionMeses'],
    nota: 'Una iguala cubre la asesoría continua y la gestión ordinaria. Incluir litigios ilimitados en una tarifa mensual sería insostenible para la firma y engañoso para el cliente.',
  },
  {
    id: 'litigio-civil-inmobiliario',
    division: 'legal',
    nombre: 'Litigio civil e inmobiliario',
    icono: 'scale',
    base: { moneda: 'USD', monto: 1000 },
    unidad: 'etapa inicial, precio base',
    plazo: 'Sujeto a los órganos jurisdiccionales competentes',
    incluye: ['Evaluación y diagnóstico documental del caso',
              'Preparación de instancias y escritos de la etapa',
              'Notificaciones y actos de alguacil del proceso',
              'Representación en la etapa contratada'],
    noIncluye: ['Etapas posteriores, que se cotizan al llegar a ellas',
                'Impuestos, tasas y derechos oficiales'],
    pago: 'Al inicio de cada etapa',
    itbisPorDefecto: true,
    campos: ['etapaProcesal', 'jurisdiccion'],
    nota: 'Precio base sujeto a análisis, sin perjuicio de cuota litis cuando aplique. Ningún profesional puede garantizar el resultado de un litigio ni el tiempo que tomará.',
    ocultarCuotaLitis: true,
  },
  {
    id: 'litigio-penal-coercion',
    division: 'legal',
    nombre: 'Litigio penal · medida de coerción',
    icono: 'shield',
    base: { moneda: 'USD', monto: 1000 },
    unidad: 'etapa inicial, precio base',
    plazo: 'Sujeto a los órganos jurisdiccionales competentes',
    incluye: ['Evaluación del expediente', 'Representación en la etapa contratada',
              'Notificaciones y actos de alguacil del proceso'],
    noIncluye: ['Etapas posteriores', 'Impuestos, tasas y derechos oficiales'],
    pago: 'Al inicio de cada etapa',
    itbisPorDefecto: true,
    campos: ['etapaProcesal'],
    nota: 'Precio base sujeto a análisis del expediente.',
    ocultarCuotaLitis: true,
  },
  {
    id: 'divorcio',
    division: 'legal',
    nombre: 'Divorcio',
    icono: 'file-text',
    base: { moneda: 'USD', monto: 1000 },
    unidad: 'por mutuo consentimiento',
    variantes: [
      { id: 'mutuo', nombre: 'Por mutuo consentimiento', monto: 1000 },
      { id: 'incompatibilidad', nombre: 'Por incompatibilidad de caracteres', monto: 1500 },
    ],
    plazo: 'Sujeto a los tribunales competentes',
    incluye: ['Redacción y depósito de los actos del procedimiento', 'Representación en el proceso'],
    noIncluye: ['Partición de bienes, que se trabaja con cuota litis',
                'Impuestos, tasas y derechos oficiales'],
    pago: '100% al inicio',
    itbisPorDefecto: true,
    campos: ['tipoDivorcio'],
  },
  {
    id: 'particion-bienes',
    division: 'legal',
    nombre: 'Partición de bienes',
    icono: 'git-branch',
    base: null,
    unidad: 'se trabaja con cuota litis',
    plazo: 'Sujeto a los tribunales competentes',
    incluye: ['Evaluación del patrimonio a partir', 'Representación en el procedimiento'],
    noIncluye: ['Impuestos, tasas y derechos oficiales'],
    pago: 'Conforme al acuerdo de cuota litis',
    itbisPorDefecto: false,
    campos: [],
    ocultarCuotaLitis: true,
  },
  {
    id: 'sucesiones',
    division: 'legal',
    nombre: 'Sucesiones',
    icono: 'users',
    base: null,
    unidad: 'cotización según el expediente',
    plazo: 'Sujeto a la DGII y al Registro de Títulos',
    incluye: ['Determinación de herederos', 'Preparación del expediente sucesoral',
              'Gestión ante las instancias correspondientes'],
    noIncluye: ['Impuesto sucesoral y tasas oficiales', 'Litigios derivados, que se cotizan aparte'],
    pago: 'Según etapas acordadas',
    itbisPorDefecto: true,
    campos: ['cantidadHerederos', 'cantidadInmuebles'],
  },
  {
    id: 'creacion-empresas',
    division: 'legal',
    nombre: 'Constitución de sociedades',
    icono: 'building',
    base: { moneda: 'USD', monto: 1000 },
    unidad: 'constitución de SRL',
    plazo: 'Sujeto a la Cámara de Comercio y a la DGII',
    incluye: ['Redacción de estatutos y documentación societaria',
              'Registro de nombre comercial', 'Registro mercantil', 'Obtención del RNC'],
    noIncluye: ['Impuestos, tasas y derechos de registro, que se facturan aparte'],
    pago: '100% al inicio',
    itbisPorDefecto: true,
    campos: ['tipoSociedad', 'cantidadSocios'],
  },
  {
    id: 'cobros-compulsivos',
    division: 'legal',
    nombre: 'Cobros compulsivos y recuperación de cartera',
    icono: 'trending-up',
    base: { moneda: 'USD', monto: 1000 },
    unidad: 'honorario base, o esquema mixto',
    modelos: [
      { id: 'A', nombre: 'Honorario fijo' },
      { id: 'B', nombre: 'Honorario fijo + porcentaje de recuperación' },
      { id: 'C', nombre: 'Iguala + porcentaje de recuperación' },
    ],
    plazo: 'Según la etapa de gestión y la vía aplicable',
    incluye: ['Diagnóstico de la cartera', 'Gestión de contacto documentada',
              'Requerimiento formal', 'Negociación y acuerdo de pago'],
    noIncluye: ['Acción judicial, que se cotiza al escalar', 'Impuestos, tasas y derechos oficiales'],
    pago: 'Según el modelo contratado',
    itbisPorDefecto: true,
    campos: ['modeloRecuperacion', 'montoCartera'],
    nota: 'La recuperabilidad de un crédito depende de la solvencia real del deudor y del respaldo documental de la acreencia. GSD evalúa ambos factores antes de proponer un modelo.',
  },
  {
    id: 'embargos-ejecuciones',
    division: 'legal',
    nombre: 'Embargos y ejecuciones',
    icono: 'gavel',
    base: null,
    unidad: 'cotización según la medida y la cuantía',
    plazo: 'Sujeto a los órganos jurisdiccionales competentes',
    incluye: ['Evaluación del título y de la exigibilidad',
              'Preparación de instancias y notificaciones', 'Seguimiento procesal'],
    noIncluye: ['Impuestos, tasas y derechos oficiales'],
    pago: 'Según etapas acordadas',
    itbisPorDefecto: true,
    campos: ['tipoMedida', 'montoAcreencia'],
    nota: 'Ninguna medida ejecutiva es automática. Antes de accionar se evalúa la existencia del título, la solvencia de la contraparte y la relación entre el costo del procedimiento y el monto recuperable.',
  },
  {
    id: 'hipotecas-garantias',
    division: 'legal',
    nombre: 'Hipotecas y préstamos con garantía',
    icono: 'lock',
    base: null,
    unidad: '10% de gastos de cierre',
    porcentaje: 10,
    baseCalculo: 'monto del préstamo',
    plazo: 'Sujeto al Registro de Títulos',
    incluye: ['Due diligence de la garantía', 'Redacción del contrato y de la garantía',
              'Inscripción de la hipoteca', 'Verificación de rango y cargas anteriores'],
    noIncluye: ['Impuestos, tasas y derechos de registro', 'Tasación del inmueble'],
    pago: 'Al cierre de la operación',
    itbisPorDefecto: true,
    campos: ['montoPrestamo', 'rolGSD'],
    admiteDescuento: true,
    nota: 'GSD presta servicios jurídicos y de estructuración documental; no realiza intermediación financiera ni capta recursos del público.',
  },

  // ─────────────────────── INMOBILIARIO ───────────────────────
  {
    id: 'transferencia-ordinaria',
    division: 'inmobiliario',
    nombre: 'Transferencia de título · ordinaria',
    icono: 'file-check',
    base: { moneda: 'USD', monto: 800 },
    unidad: 'por transferencia',
    plazo: '5 días hábiles para depositar en Registro de Títulos desde la documentación completa, sin perjuicio del tiempo del Registro',
    incluye: ['Revisión documental completa',
              'Certificación de estado jurídico (tasa RD$1,000 cubierta por GSD)',
              'Constancia de IPI gestionada y cubierta por GSD',
              'Legalización de firmas cubierta por GSD',
              'Redacción del poder de representación si hace falta',
              'Depósito y seguimiento ante el Registro de Títulos'],
    noIncluye: ['Redacción del contrato de compraventa',
                'Impuesto de transferencia del 3%, fijado por la DGII sobre su avalúo',
                'Notarización, que varía según el monto (≈ US$100)',
                'Tasación y levantamiento de cargas, que se cotizan aparte'],
    pago: '100% al inicio',
    itbisPorDefecto: true,
    campos: ['designacionCatastral', 'valorInmueble'],
  },
  {
    id: 'transferencia-confotur',
    division: 'inmobiliario',
    nombre: 'Transferencia de título · CONFOTUR',
    icono: 'sun',
    base: { moneda: 'USD', monto: 1500 },
    unidad: 'por transferencia',
    plazo: '5 días hábiles para depositar en Registro de Títulos desde la documentación completa',
    incluye: ['Revisión documental completa',
              'Certificación de estado jurídico y constancia de IPI cubiertas por GSD',
              'Legalización de firmas cubierta por GSD',
              'Verificación del alcance del régimen sobre la unidad adquirida',
              'Depósito y seguimiento ante el Registro de Títulos'],
    noIncluye: ['Certificaciones CONFOTUR del proyecto, que aporta el cliente',
                'Notarización según el monto',
                'Tasación y levantamiento de cargas'],
    pago: '100% al inicio',
    itbisPorDefecto: true,
    campos: ['designacionCatastral', 'proyectoConfotur', 'valorInmueble'],
    nota: 'Bajo el régimen CONFOTUR el comprador no paga el 3% de impuesto de transferencia. No hay devolución de honorarios si la exención no procede por causas ajenas a la firma.',
  },
  {
    id: 'transferencia-vehiculo',
    division: 'inmobiliario',
    nombre: 'Transferencia de vehículo de motor',
    icono: 'truck',
    base: { moneda: 'DOP', monto: 25000 },
    unidad: 'por vehículo',
    plazo: '10 días hábiles desde la documentación completa, sin perjuicio de los tiempos de la DGII u otras instituciones',
    incluye: ['Redacción del acto de venta',
              'Verificación de titularidad y cargas',
              'Gestión de la certificación de Plan Piloto',
              'Tasa de matrícula cubierta por GSD',
              'Asistencia ante las autoridades correspondientes'],
    noIncluye: ['Oposiciones o gravámenes, que se cotizan aparte',
                'Multas, recargos o deudas asociadas al vehículo',
                'Revisión mecánica o peritaje técnico'],
    desglose: [
      { concepto: 'Honorario profesional GSD', moneda: 'DOP', monto: 25000, quien: 'GSD' },
      { concepto: 'Impuesto de transferencia (2% sobre valor de referencia DGII)', moneda: 'DOP', monto: null, quien: 'DGII' },
      { concepto: 'Certificación de Plan Piloto', moneda: 'DOP', monto: 2500, quien: 'Tercero' },
      { concepto: 'Notarización', moneda: 'DOP', monto: 2000, quien: 'Tercero' },
      { concepto: 'Legalización de firmas', moneda: 'DOP', monto: 800, quien: 'Tercero' },
    ],
    pago: 'Únicamente por transferencia bancaria',
    itbisPorDefecto: true,
    campos: ['marcaModelo', 'chasis', 'valorReferencia'],
  },
  {
    id: 'venta-inmueble',
    division: 'inmobiliario',
    nombre: 'Venta de inmuebles · intermediación',
    icono: 'home',
    base: null,
    unidad: '5% del valor de la venta',
    porcentaje: 5,
    baseCalculo: 'valor de la venta',
    plazo: 'Según la comercialización',
    incluye: ['Análisis documental previo del inmueble',
              'Preparación y corrección de lo que impide transferir',
              'Comercialización y negociación',
              'Coordinación del cierre'],
    noIncluye: ['Redacción del contrato de venta, que es un servicio distinto (1–3% del monto)',
                'Honorarios legales de la transferencia',
                'Impuestos y tasas oficiales'],
    pago: 'Al cierre de la operación',
    itbisPorDefecto: true,
    campos: ['valorVenta', 'tipoInmueble'],
    nota: 'La comisión de intermediación, los honorarios legales por la transferencia y los impuestos y tasas oficiales son conceptos distintos y se presentan siempre desglosados al cliente.',
  },
  {
    id: 'contrato-venta',
    division: 'inmobiliario',
    nombre: 'Contrato de compraventa',
    icono: 'edit',
    base: null,
    unidad: 'de 1% a 3% del monto de la operación',
    porcentaje: 2,
    baseCalculo: 'monto de la operación',
    plazo: 'Según la complejidad del instrumento',
    incluye: ['Redacción del contrato sobre la operación real',
              'Verificación de la identificación del inmueble y de la legitimación de las partes',
              'Condiciones suspensivas y resolutorias con efectos verificables'],
    noIncluye: ['Transferencia del título, que es un servicio distinto',
                'Impuestos, tasas y derechos oficiales'],
    pago: '100% al inicio',
    itbisPorDefecto: true,
    campos: ['montoOperacion'],
  },
  {
    id: 'compra-segura',
    division: 'inmobiliario',
    nombre: 'Compra Segura · plan por etapas',
    icono: 'shield-check',
    base: null,
    unidad: 'plan por etapas o completo por adelantado',
    plazo: 'Según la etapa contratada',
    etapas: [
      { id: 1, nombre: 'Etapa 1 · Verificación', alcance: 'Due diligence documental, registral y técnica del inmueble.' },
      { id: 2, nombre: 'Etapa 2 · Contrato', alcance: 'Redacción o revisión del contrato. No aplica en proyectos de desarrollador donde GSD no redacta el contrato.' },
      { id: 3, nombre: 'Etapa 3 · Transferencia', alcance: 'Transferencia del título hasta su inscripción.' },
    ],
    incluye: ['Las etapas efectivamente contratadas'],
    noIncluye: ['Impuestos, tasas y derechos oficiales'],
    pago: 'Cada etapa al inicio, o plan completo por adelantado con 15% de descuento',
    itbisPorDefecto: true,
    campos: ['modalidadCompraSegura', 'cantidadPropiedades', 'valorInmueble'],
    nota: 'Si GSD desaconseja la compra, el cliente solo paga la Etapa 1. En la modalidad de plan completo por adelantado se pueden verificar hasta 3 propiedades; si tras las 3 el cliente no compra, se devuelve la parte ligada al valor del inmueble (contrato y transferencia) con retención del 10% sobre ese concepto.',
  },
  {
    id: 'due-diligence',
    division: 'inmobiliario',
    nombre: 'Due diligence inmobiliario',
    icono: 'search',
    base: { moneda: 'USD', monto: 1000 },
    unidad: 'por inmueble',
    plazo: 'Al menos 10 días hábiles desde la documentación completa',
    incluye: ['Análisis jurídico, registral y catastral',
              'Verificación técnica de la realidad física del inmueble',
              'Informe de riesgo con clasificación de semáforo'],
    noIncluye: ['Levantamiento topográfico completo, que se cotiza aparte',
                'Impuestos, tasas y derechos oficiales'],
    pago: '100% al inicio',
    itbisPorDefecto: true,
    campos: ['designacionCatastral', 'cantidadInmuebles'],
    nota: 'Ningún estudio puede garantizar la inexistencia absoluta de contingencias no detectables a partir de la información accesible al momento de su elaboración.',
  },
  {
    id: 'condominio',
    division: 'inmobiliario',
    nombre: 'Constitución de condominio',
    icono: 'layers',
    base: null,
    unidad: 'cotización según número de unidades',
    plazo: 'Sujeto a Mensuras Catastrales y al Registro de Títulos',
    incluye: ['Redacción del reglamento y documentación del régimen',
              'Coordinación técnica con agrimensura',
              'Planos de deslinde de unidades',
              'Asistencia en los procesos registrales correspondientes'],
    noIncluye: ['Impuestos, tasas y derechos oficiales',
                'Administración posterior del condominio, que se contrata aparte'],
    pago: '50% al inicio, 50% contra aprobación',
    itbisPorDefecto: true,
    campos: ['cantidadUnidades', 'superficieTotal'],
  },
  {
    id: 'asesoria-inmobiliaria',
    division: 'inmobiliario',
    nombre: 'Asesoría inmobiliaria',
    icono: 'message-square',
    base: null,
    unidad: 'cotización según alcance',
    plazo: 'Según el alcance contratado',
    incluye: ['Análisis de la operación', 'Recomendación de ruta documentada'],
    noIncluye: ['Ejecución de los trámites, que se cotiza aparte'],
    pago: '100% al inicio',
    itbisPorDefecto: true,
    campos: [],
  },

  // ─────────────────────── AGRIMENSURA ───────────────────────
  {
    id: 'deslinde-catastral',
    division: 'agrimensura',
    nombre: 'Deslinde catastral',
    icono: 'map',
    base: { moneda: 'USD', monto: 2000, alterna: { moneda: 'DOP', monto: 120000 } },
    unidad: 'parcelas de hasta 1,000 m²',
    plazo: 'Estimado de 4 meses, no comprometido, sujeto a Mensuras, Tribunal y Registro',
    incluye: ['Diligencia y certificación de estado jurídico',
              'Trabajo de campo con equipo GNSS',
              'Elaboración de planos',
              'Notificación a colindantes',
              'Impuestos, tasas por servicio, sellos y recibos del procedimiento'],
    noIncluye: ['Impuesto del 3% de transferencia de constancia anotada, que la DGII liquida sobre su avalúo',
                'Oposición de colindantes, que se cotiza aparte'],
    pago: '100% al inicio (preferente) o 50% inicial y 50% contra aprobación del plano por Mensuras',
    itbisPorDefecto: true,
    campos: ['designacionCatastral', 'superficieM2', 'zona'],
    nota: 'La gestión del 3% de transferencia de constancia anotada la realiza GSD sin cargo adicional. El escalamiento por superficies mayores a 1,000 m² se cotiza de forma individual.',
  },
  {
    id: 'regularizacion-parcelaria',
    division: 'agrimensura',
    nombre: 'Regularización parcelaria',
    icono: 'grid',
    base: { moneda: 'USD', monto: 2000, alterna: { moneda: 'DOP', monto: 120000 } },
    unidad: 'parcelas de hasta 1,000 m²',
    plazo: 'Estimado de 4 meses, no comprometido, sujeto a Mensuras, Tribunal y Registro',
    incluye: ['Diligencia y certificación de estado jurídico',
              'Trabajo de campo con equipo GNSS',
              'Elaboración de planos',
              'Notificación a colindantes',
              'Impuestos, tasas por servicio, sellos y recibos del procedimiento'],
    noIncluye: ['Impuesto del 3% de transferencia de constancia anotada',
                'Oposición de colindantes'],
    pago: '100% al inicio (preferente) o 50% inicial y 50% contra aprobación del plano',
    itbisPorDefecto: true,
    campos: ['designacionCatastral', 'superficieM2', 'zona'],
    nota: 'Es el mismo trabajo que el deslinde catastral con otro nombre y la misma tarifa, cuando cumpla los requisitos de Mensuras y del Registro de Títulos.',
  },
  {
    id: 'replanteo-verificacion',
    division: 'agrimensura',
    nombre: 'Replanteo y verificación de área',
    icono: 'crosshair',
    base: { moneda: 'USD', monto: 500, alterna: { moneda: 'DOP', monto: 30000 } },
    unidad: 'áreas de hasta 1,000 m² en Punta Cana y La Romana',
    plazo: 'Visita de campo dentro de la semana siguiente e informe técnico a los 7 días hábiles de la visita',
    incluye: ['Desplazamiento dentro del radio de Punta Cana y La Romana',
              'Trabajo de campo con equipo GNSS',
              'Marcación provisional de vértices',
              'Informe técnico que certifica conformidad o detalla desplazamiento, superposición o asunto litigioso con su alcance'],
    noIncluye: ['Monumentación con mojones',
                'Rectificación de plano o de título, que es un servicio aparte',
                'Desplazamiento fuera de zona o superficies mayores, con costo adicional'],
    documentosCliente: ['Copia del plano aprobado', 'Copia del certificado de título'],
    pago: '100% al inicio',
    itbisPorDefecto: true,
    campos: ['designacionCatastral', 'superficieM2', 'zona'],
  },
  {
    id: 'investigacion-parcelaria',
    division: 'agrimensura',
    nombre: 'Investigación parcelaria',
    icono: 'file-search',
    base: { moneda: 'DOP', monto: 12000 },
    unidad: 'por parcela',
    plazo: 'Según la disponibilidad de los antecedentes',
    incluye: ['Verificación preliminar y resumida del estado de la parcela',
              'Determinación de si un trabajo posterior procede antes de contratarlo'],
    noIncluye: ['Trabajo de campo', 'Impuestos, tasas y derechos oficiales'],
    pago: '100% al inicio',
    itbisPorDefecto: true,
    campos: ['designacionCatastral'],
    nota: 'Verificación preliminar. Su función es determinar si un trabajo mayor procede antes de que el cliente lo contrate.',
  },
  {
    id: 'levantamiento-topografico',
    division: 'agrimensura',
    nombre: 'Levantamiento topográfico y curvas de nivel',
    icono: 'mountain',
    base: null,
    unidad: 'cotización según superficie, ubicación y accesibilidad',
    plazo: 'Según superficie y condiciones del terreno',
    incluye: ['Trabajo de campo con equipo GNSS RTK',
              'Procesamiento de la información',
              'Plano topográfico con curvas de nivel',
              'Memoria técnica del levantamiento'],
    noIncluye: ['Trámites registrales derivados', 'Impuestos, tasas y derechos oficiales'],
    pago: '50% al inicio, 50% contra entrega',
    itbisPorDefecto: true,
    campos: ['superficieM2', 'zona', 'equidistanciaCurvas'],
    nota: 'El grado de precisión alcanzable depende del equipo empleado, del método aplicado, de las condiciones del terreno y del propósito del levantamiento. GSD define y documenta estas condiciones en cada proyecto.',
  },
  {
    id: 'subdivision-planos',
    division: 'agrimensura',
    nombre: 'Subdivisiones, refundiciones y planos de proyecto',
    icono: 'scissors',
    base: null,
    unidad: 'cotización según número de resultantes y superficie',
    plazo: 'Sujeto a Mensuras Catastrales y al Registro de Títulos',
    incluye: ['Trabajo de campo con equipo GNSS',
              'Elaboración de planos de las parcelas resultantes',
              'Gestión ante Mensuras Catastrales'],
    noIncluye: ['Impuestos, tasas y derechos oficiales', 'Oposiciones, que se cotizan aparte'],
    pago: '50% al inicio, 50% contra aprobación del plano',
    itbisPorDefecto: true,
    campos: ['designacionCatastral', 'superficieM2', 'cantidadResultantes'],
  },
];

const DIVISIONES = [
  { id: 'legal', nombre: 'GSD Legal', descripcion: 'Protección jurídica. Estructuración. Litigios.' },
  { id: 'inmobiliario', nombre: 'GSD Property', descripcion: 'Propiedades. Inversión. Operaciones.' },
  { id: 'agrimensura', nombre: 'GSD Survey', descripcion: 'Precisión técnica. Tierra. Georreferenciación.' },
];

/** Texto fijo que se imprime en toda cotización. */
const TERMINOS_GENERALES = [
  'Los montos indicados son preliminares y quedan sujetos a la complejidad del caso y al análisis previo del expediente.',
  'Los honorarios de GSD, los impuestos y tasas oficiales y los gastos de operación son conceptos distintos y se presentan siempre desglosados.',
  'GSD no garantiza resultados judiciales ni administrativos, ni plazos de tramitación ante órganos competentes.',
  'Esta cotización no constituye oferta vinculante. Prevalece el contrato de servicios suscrito entre las partes.',
];

function buscarServicio(id) {
  return SERVICIOS.find((s) => s.id === id) || null;
}

function serviciosPorDivision() {
  return DIVISIONES.map((d) => ({
    ...d,
    servicios: SERVICIOS.filter((s) => s.division === d.id),
  }));
}

module.exports = {
  MONEDA,
  SERVICIOS,
  DIVISIONES,
  TERMINOS_GENERALES,
  buscarServicio,
  serviciosPorDivision,
  monedaSugerida,
};
